### ISSUE TITLE
Nano S+

### ISSUE THREAD

**Issue by teacoat** [LedgerHQ/udev-rules#15]
I can't seem to get my S+ to connect, I think these rules need updating to support it?

**Comment by thall** [comment]
It's this [one](https://github.com/LedgerHQ/udev-rules/blob/master/add_udev_rules.sh#L16)

**Comment by loupiote** [comment]
Maybe change "Ledger Test" in "Nano S plus" in the comments in the udev file?

**Comment by mvo5** [comment]
Thanks, it would be great if the relevant usb id could be changed from "Ledger Test" to "Nano S plus" for the relevant usb id. We want to add support to the snapd to support this better on Ubuntu,Debian,Fedora etc in https://github.com/snapcore/snapd/pull/12313/ and ideally there would be a clear upstream repo that indicates that the ID is correct.

**Comment by xchapron-ledger** [comment]
Closing as it has been updated in here and in snapd
