### ISSUE TITLE
udev Rules Clarification For My PR To The Ubuntu snap Repository

### ISSUE THREAD

**Issue by taoteh1221** [LedgerHQ/udev-rules#20]
I have submitted a PR to Ubuntu's snap repository, to add support for the Nano S Plus (as FireFox is now run as a snap package as of Ubuntu 22.X). They are looking for clarification on the comment in the current udev rules, where the Nano S Plus pci-id is listed under the comment "Ledger Test"...

PR in Ubuntu's snap Repository:
https://github.com/snapcore/snapd/pull/12313

PR Review Comment Seeking Clarification:
https://github.com/snapcore/snapd/pull/12313#discussion_r1022480144

udev Rules To Clarify:
https://github.com/LedgerHQ/udev-rules/blob/master/add_udev_rules.sh#L15

**Comment by taoteh1221** [comment]
Bump, anybody managing this repo?

**Comment by adrienlacombe-ledger** [comment]
yes, we will come back to you.

**Comment by taoteh1221** [comment]
> yes, we will come back to you.

Thanks.

**Comment by xchapron-ledger** [comment]
Closing as old and fixed
