### ISSUE TITLE
Fedora 37

### ISSUE THREAD

**Issue by Kwaskoff** [LedgerHQ/udev-rules#24]
after script executed - Ledger S still doesn't work

Version 112.0.5615.121 (Official Build) Fedora Project (64-bit)
se 2.1.0 mc 1.12 bl 0.11

**Comment by Kwaskoff** [comment]
it turned out that this is not a fully plugged USB connector

**Comment by rogerioduboyduboy-sudo** [comment]
#atualização 
#gratidão
