### ISSUE TITLE
Recent changes break compatibility with fix/ledger-vagrant

### ISSUE THREAD

**Issue by christophersanborn** [LedgerHQ/udev-rules#4]
I am developing an app for the Ledger Nano S and our build environment runs inside a VM based on [fix/ledger-vagrant](https://github.com/fix/ledger-vagrant) (An Ubuntu 16.04 VM that automatically provisions the the BOLOS SDK, ledgerblue, compiler ABI's, etc.)

Recently, I found I was unable to deploy new VM's and connect to Nano from inside the VM.  It's not a failure of USB mapping into the VM, because the Nano will show up with `lsusb`.  The IOError occurs, e.g., when attempting to load the compiled app onto the device with `make load`.  (Error logs at end of issue.)

I was able to trace the source of the issue to changes in LedgerHQ/udev-rules.  In particular, if I revert to an earlier version of the rules (5/3/2018) by running the following inside the VM:

`wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/20cc1651eb551c4855aaa56628c77eaeb3031c22/add_udev_rules.sh | sudo bash` 

Then the problem is resolved.

However, because of the discussion [here](https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/), I am unsure as to whether this is a case of "the new rules are broken" or whether there is some change I need to make in my dev environment and setup documentation to be able to deploy working VMs. I am hoping for advice from the community here.

Error log from `make load` follows:

```
$ make load
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100003
BOLOS_ENV=/opt/bolos
python -m ledgerblue.loadApp --appFlags 0x40 --path "48'/1'" --curve secp256k1 --tlv --targetId 0x31100003 --delete --fileName bin/app.hex --appName BitShares --appVersion 0.0.1 --dataSize `cat debug/app.map |grep _nvram_data_size | tr -s ' ' | cut -f2 -d' '` `ICONHEX=\`python /opt/bolos/nanos-secure-sdk/icon.py nanos_app_bts.gif hexbitmaponly 2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"`  
Generated random root public key : 04f1d3e4bdb98addf9f92b257c0fb08e80f51fccb4c3b48fddbf2839344a13af42bc43351699f9b8dc43fbee64fabf60065c83dd8e13ee80750c1999dbf6a2cd57
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ledgerblue/loadApp.py", line 171, in <module>
    dongle = getDongle(args.apdu)
  File "/usr/local/lib/python2.7/dist-packages/ledgerblue/comm.py", line 212, in getDongle
    dev.open_path(hidDevicePath)
  File "hid.pyx", line 72, in hid.device.open_path
IOError: open failed
make: *** [load] Error 1
```

**Comment by jleni** [comment]
Yes, this is because the new version is using `uaccess`. Vagrant typically uses ssh and that does not trigger udev. It would work if you actually login in virtualbox.

A temporary workaround I am using is to append `MODE="0660", GROUP="plugdev"` to each line in `20-hw1.rules`

**Comment by vyoz** [comment]
The latest version doesn't work on ubuntu 18.04 (not vagrant/vm) either. I have to use the previous version (commit-id: 709581c85db97bf6ea12e472aa4e350bf0eabfb7) to get it work.
